### ISSUE TITLE
[docker-BUG] 容器启动失败 ModuleNotFoundError: No module named 'scripts'

### ISSUE THREAD

**Issue by huangbaichao** [Physton/sd-webui-prompt-all-in-one-app#3]
<img width="842" alt="image" src="https://github.com/Physton/sd-webui-prompt-all-in-one-app/assets/9191067/2b589a3e-2d30-4820-bccb-5b09b3cb7a00">
<img width="718" alt="image" src="https://github.com/Physton/sd-webui-prompt-all-in-one-app/assets/9191067/2f9536b4-e60d-4bde-afd2-29d5f9a49e47">

**Comment by Physton** [comment]
docker编译的确实有问题，我尽快修复。

**Comment by huangbaichao** [comment]
> docker编译的确实有问题，我尽快修复。

docker 运行可以了。compose不行，目前可以先继续使用。

**Comment by Physton** [comment]
docker run 可以，docker-compose 不行是吧？

**Comment by Physton** [comment]
https://github.com/Physton/sd-webui-prompt-all-in-one-app/releases/tag/base.9e6f1b2-from.627a741

已修复问题，已重新编译Docker。
