### ISSUE TITLE
TagComplete功能无法扫描csv文件

### ISSUE THREAD

**Issue by ryxiang** [Physton/sd-webui-prompt-all-in-one-app#4]
TagComplete功能无法扫描csv文件，[sd-webui-prompt-all-in-one-app](https://github.com/Physton/sd-webui-prompt-all-in-one-app)是手动安装，按照提示把文件名改为extensions重启，也还是扫描不到
![image](https://github.com/Physton/sd-webui-prompt-all-in-one-app/assets/52651563/339a725b-f1dd-4713-913e-1c7047f65006)
![image](https://github.com/Physton/sd-webui-prompt-all-in-one-app/assets/52651563/bff1f179-b901-4e70-abaa-3c6636bfe149)
![image](https://github.com/Physton/sd-webui-prompt-all-in-one-app/assets/52651563/bbba369b-cea3-4e0b-8b03-cb6a7d72c45a)

**Comment by Physton** [comment]
https://github.com/Physton/sd-webui-prompt-all-in-one-app/releases/tag/20231126.base.d673367-from.6e4f3cd

已修复，请更新。
